#!/bin/sh

#
# This script updates the SG-3100 device's first LED with gateway status
#
# Based on tcsh script by msf2000 on this thread https://forum.netgate.com/topic/122407/netgate-sg-3100-leds
# Finding gpio device based on https://github.com/justdaniel-gh/sg3100customleds/commit/ddbf412cb1cf3ba32160972e2177c356611ff57f
#

# gpio device number
# A way to get the gpio device that controls the led lights (its not always 0)
gdev="/dev/gpioc$(sysctl dev.gpio | grep .led. | cut -d . -f 3 | uniq)"

# based on gwstatus, set color of first LED
# led a  -  led b  -  led c
# 6 7 8  -  3 4 5  -  0 1 2 

set_leds () {
    case ${1} in
	"a")
	    red=6
	    green=7
	    blue=8
	    ;;
	"b")
	    red=3
	    green=4
	    blue=5
	    ;;
	"c")
	    red=0
	    green=1
	    blue=2
	    ;;
    esac

    case ${2} in
	"down"|"none")
	    # Down
	    /usr/sbin/gpioctl -f ${gdev} ${red} duty 16
	    /usr/sbin/gpioctl -f ${gdev} ${green} duty 0
	    /usr/sbin/gpioctl -f ${gdev} ${blue} duty 0
	    ;;
	"online")
	    # Online, look at substates
	    case ${3} in
		"none")
		    /usr/sbin/gpioctl -f ${gdev} ${red} duty 0
		    /usr/sbin/gpioctl -f ${gdev} ${green} duty 16
		    /usr/sbin/gpioctl -f ${gdev} ${blue} duty 0
		    ;;
		"force_down")
		    /usr/sbin/gpioctl -f ${gdev} ${red} duty 0
		    /usr/sbin/gpioctl -f ${gdev} ${green} duty 0
		    /usr/sbin/gpioctl -f ${gdev} ${blue} duty 16
		    ;;
		*)
		    # Includes high_delay, high_loss, delay, loss
		    /usr/sbin/gpioctl -f ${gdev} ${red} duty 16
		    /usr/sbin/gpioctl -f ${gdev} ${green} duty 4
		    /usr/sbin/gpioctl -f ${gdev} ${blue} duty 0
		    ;;
	    esac
	    ;;
	*)
	    # Unknown
	    /usr/sbin/gpioctl -f ${gdev} ${red} duty 0
	    /usr/sbin/gpioctl -f ${gdev} ${green} duty 0
	    /usr/sbin/gpioctl -f ${gdev} ${blue} duty 16
	    ;;
    esac
}

verbose () {
    test -z "$do_verbose" && return

    echo "V: ${*}" >&2
}

gw_a=
gw_b=
gw_c=
do_verbose=

OPTIONS=$(getopt "a:b:c:v" $*) || exit 1
set -- ${OPTIONS}
while true; do
    case ${1} in
	"-a")
	    gw_a="${2}"
	    shift 2
	    ;;
	"-b")
	    gw_b="${2}"
	    shift 2
	    ;;
	"-c")
	    gw_c="${2}"
	    shift 2
	    ;;
	"-v")
	    do_verbose='-v'
	    shift
	    ;;
	--)
	   shift
	   break
	   ;;
	*)
	  echo "Internal error!" >&2
	  exit 1
	  ;;
    esac
done

# 21.05x
# /usr/local/bin/php /usr/local/sbin/pfSsh.php playback gatewaystatus
# Name           Monitor        Source              Delay   StdDev  Loss  Status  Substatus
# WAN_EA_DHCP    38.145.154.1   38.145.155.206    2.188ms  0.236ms  0.0%  online       none
# WAN_OTTC_DHCP  192.190.166.1  192.190.166.60     0.74ms  0.177ms  0.0%  online       none

/usr/local/bin/php /usr/local/sbin/pfSsh.php playback gatewaystatus | \
    while read name monitor source delay stddev loss status substatus; do
	test "${name}" == "Name" && continue
	verbose "Name: ${name} ${source}->${monitor} Delay: ${delay} Stdev: ${stdev} Loss: ${loss} Status: ${status} Substatus: ${substatus}"
	if [ "${name}" == "${gw_a}" ]; then
	    set_leds "a" "${status}" "${substatus}"
	elif [ "${name}" == "${gw_b}" ]; then
	    set_leds "b" "${status}" "${substatus}"
	elif [ "${name}" == "${gw_c}" ]; then
	    set_leds "c" "${status}" "${substatus}"
	else
	    echo "Gateway ${name} not matched" 2>&1
	fi
    done

exit 0
